apiVersion: v1
kind: Pod
metadata:
  annotations:
    timezone.jugglechat.io/injected: "true"
    timezone.jugglechat.io/timezone: UTC
  labels:
    name: nginx-test
  name: nginx-test
spec:
  containers:
  - env:
    - name: TZ
      value: UTC
    image: nginx
    name: nginx-test
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
    volumeMounts:
    - mountPath: /etc/localtime
      name: webhook
      readOnly: true
      subPath: UTC
    - mountPath: /usr/share/zoneinfo
      name: webhook
      readOnly: true
  volumes:
  - hostPath:
      path: /usr/share/zoneinfo
    name: webhook
