apiVersion: v1
kind: Pod
metadata:
  annotations:
    timezone.jugglechat.io/injected: "true"
    timezone.jugglechat.io/timezone: Asia/Shanghai
  labels:
    name: nginx-test
  name: nginx-test
spec:
  containers:
  - env:
    - name: TZ
      value: Asia/Shanghai
    image: nginx
    name: nginx-test
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
    volumeMounts:
    - mountPath: /etc/localtime
      name: zoneinfo-configmap
      readOnly: true
      subPath: Shanghai
  volumes:
  - configMap:
      name: ms.zoneinfo.configmap.name
    name: zoneinfo-configmap
