kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "service-webhook.fullname" . }}-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "service-webhook.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "service-webhook.fullname" . }}-role-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "service-webhook.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "service-webhook.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: {{ include "service-webhook.fullname" . }}-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "service-webhook.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "service-webhook.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
