apiVersion: v1
kind: Service
metadata:
  name: {{ include "service-webhook.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "service-webhook.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "service-webhook.selectorLabels" . | nindent 4 }}
